name: Deploy to Staging Subdomain

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Staging Subdomain
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 193.203.185.160
          username: u764122208.staging.darshantrust.co.in
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          local-dir: ./build
          server-dir: /public_html/