name: Deploy to Hostinger

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build CRA app
        run: npm run build

      - name: SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            # Navigate to the public_html directory
            cd /public_html/

            # Remove existing files
            rm -rf *

            # Upload built CRA app
            upload ./build

            # Change permissions
            chmod -R 755 /public_html/
